version: '3'
services:

  redis:
    image: redis
    ports:
      - "6379:6379"

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - storage:/app/storage
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0
      DEFAULT_HOST: http://localhost:3000

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - storage:/app/storage
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0
      DEFAULT_HOST: http://localhost:3000

volumes:
  storage:
